### ISSUE TITLE
Immutable OS: permissions issue

### ISSUE THREAD

**Issue by LukeVader-IV** [flathub/org.wireshark.Wireshark#117]
Hi,

I am using Fedora Silverblue, and when wireshark is run, i get the following error:

![image](https://user-images.githubusercontent.com/15455108/201926255-4af7112d-a9f5-44c7-87b2-8be6b7d839f9.png)

I suspect this is caused by the fact i am using an operating system with an immutable filesystem, as i didn't get this error on fedora workstation. the wireshark group does not exist.

I have no idea how this could be fixed, or if this is even the right place for this issue. i was unsure if i should post this here or on the wireshark gitlab.

**Comment by muelli** [comment]
nah, this is https://github.com/flathub/org.wireshark.Wireshark/issues/27, no?

**Comment by LukeVader-IV** [comment]
my apologies, i don't know how i missed it, but this is identical to #66 and thus a duplicate of #4
thus i will close this issue

PS: is #4 and #27 not the exact same issue?
