### ISSUE TITLE
Update to Wireshark 4.2.4

### ISSUE THREAD

**Issue by carif** [flathub/org.wireshark.Wireshark#181]
Update the package to [Wireshark 4.2.4](https://www.wireshark.org/docs/relnotes/wireshark-4.2.4.html).

**Comment by AJCxZ0** [comment]
Now to [4.2.5](https://www.wireshark.org/docs/relnotes/wireshark-4.2.5.html)

**Comment by muelli** [comment]
https://github.com/flathub/org.wireshark.Wireshark/commit/0e737063353a94a9fd9a71f452c805092dae0646
