### ISSUE TITLE
org.kde.Platform branch 6.5 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/org.wireshark.Wireshark#182]
Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK

**Comment by muelli** [comment]
https://github.com/flathub/org.wireshark.Wireshark/commit/d75d4b2938bed49f91f483aa5b175cdd5c8143d3
