### ISSUE TITLE
Not able to capture packets 

### ISSUE THREAD

**Issue by byteshiva** [flathub/org.wireshark.Wireshark#27]
Am I missing something here . why would I reconfigure using dpkg when I have installed using flatpak 

![image](https://user-images.githubusercontent.com/10637299/98488992-277b8080-2252-11eb-9f16-7d378d837f14.png)

**Comment by kurobeats** [comment]
Hey, relates to https://github.com/flathub/org.wireshark.Wireshark/issues/4, you are better off installing from your distro's repo, this version of Wireshark is not really more than a toy - it won't be able to capture packets.

**Comment by felipehw** [comment]
It isn't a toy. We can capture with `tcpdump` and analyze it in real time.

I'm using it with Fedora Silverblue and works well with this workaround to analyse capture in real time:

1. Create a *named pipe*: `mkfifo /tmp/named_pipe`
1. Thrown the real-time capture to the *named pipe*: `tcpdump -n -w - -U -i eth0 > /tmp/named_pipe`
1. Read the real-time capture from the *named pipe* as it was an interface: `org.wireshark.Wireshark -k -i /tmp/named_pipe`

**Comment by muelli** [comment]
let me close this as #4 has just been addressed.

**Comment by byteshiva** [comment]
Still not working, 

![image](https://user-images.githubusercontent.com/10637299/226078386-fd97a85a-0241-4453-94a8-864c9723e431.png)
