### ISSUE TITLE
Unable to export packet dissection

### ISSUE THREAD

**Issue by suhancz** [flathub/org.wireshark.Wireshark#28]
When trying to export (say, in JSON format) a Packet Dissection I loaded from a file (I'm [debugging an issue through another computer](https://github.com/pwr-Solaar/Solaar/issues/1084#issuecomment-782901402)), I get the error message `The file "mycapture.json" could not be created: Read-only file system.` in my home folder. If I try to export to `/tmp`, the file gets saved *somewhere*, but not directly to my system's `/tmp` directory. Can you please address this issue and meanwhile let me know as a workaround, where this "virtual" `/tmp` persists. Thank you in advance.

**Comment by muelli** [comment]
The manifest says this:  https://github.com/flathub/org.wireshark.Wireshark/blob/065a3829dc3313481f0d422d53db3626d41abbd5/org.wireshark.Wireshark.yml#L16

check whether ~/Public/ works. Or run smth like `flatpak run --filesystem=home org.wiresharkWireshark` to expose your whole home directory. The flatpak documentation should tell how to make that persistent (hint: override).

Does that help?

**Comment by ajmeese7** [comment]
+1 with the `/tmp` directory, wheneverI select that the data doesn't actually appear there. Not sure where the Wireshark temp directory would be located; the app is installed with Snap on my install, so maybe it's located in a VFS?
