### ISSUE TITLE
Build with lua5.2

### ISSUE THREAD

**Issue by lal12** [flathub/org.wireshark.Wireshark#52]
#1 indicates that lua is included, however apparently this isn't the case. My lua plugins are not loaded and the Lua submenu is missing under Tools.

**Comment by muelli** [comment]
I can't build Lua 5.2:

https://github.com/flathub/org.wireshark.Wireshark/blob/831a04d7d20bddfd05e1bd37634702bc158ee616/org.wireshark.Wireshark.yml#L83

**Comment by hfiguiere** [comment]
do you need 5.2? 5.3 is in shared-module and would make this easier.

**Comment by lal12** [comment]
> do you need 5.2? 5.3 is in shared-module and would make this easier.

AFAIK wireshark only supports 5.2

**Comment by lal12** [comment]
> I can't build Lua 5.2:

By "can't" you mean there was some error during build? I personally never had any major issue with building lua.
I will look into it, but I am not really familiar with the flatpak build system.

**Comment by muelli** [comment]
https://github.com/flathub/org.wireshark.Wireshark/commit/62315c6e480de9c6ada9955a7949834501fce003
