### ISSUE TITLE
WireShark unable to detect Wifi Adapter?

### ISSUE THREAD

**Issue by byteshiva** [flathub/org.wireshark.Wireshark#57]
WireShark unable to detect Wifi Adaptor under the normal user?

```
$ uname -a
Linux 5.8.0-3-amd64 #1 SMP Debian 5.8.14-1~mx19+2 (2020-10-25) x86_64 GNU/Linux

```

![image](https://user-images.githubusercontent.com/10637299/121775025-caa6c680-cba2-11eb-842e-aee2eb916ee1.png)

**Comment by muelli** [comment]
yeah, privileged operations are a bit tricky.
You may get around this by allowing `--device=all` and chowning the device to your user.

**Comment by byteshiva** [comment]
I see the below permission are in place for Wireshark, How do I give `chown` wifi device to my user in flatpak for `org.wireshark.Wireshark`?
```
flatpak info --show-permissions org.wireshark.Wireshark 
[Context]
shared=ipc;
sockets=x11;wayland;
devices=dri;
filesystems=xdg-config/kdeglobals:ro;xdg-public-share;home:ro;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk
```

By adding `--share=network` it shows the wifi 
![image](https://user-images.githubusercontent.com/10637299/125816929-0842436f-0637-4231-8c70-abfb9fb35b31.png)


```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --device=all --share=network --command=wireshark --file-forwarding org.wireshark.Wireshark @@ %f @@
```

Also in the documentation, I see `--device=all` is not the ideal solution.
```
While not ideal, --device=all can be used to access devices like controllers or webcams.
```

**Comment by muelli** [comment]
let me close this as #4 has been addressed.

**Comment by byteshiva** [comment]
Hello everyone, I wanted to share a blog post that I recently wrote that addresses this issue. The blog post can be found at [[How to Capture Packets Using Flatpak Wireshark](https://medium.com/@byteshiva/how-to-capture-packets-on-using-flatpak-wireshark-directly-from-tcpdump-on-host-system-f1ae3d0d0e3b)]. In the post, I provide a step-by-step guide on how to resolve the issue, along with some additional tips and tricks. I hope you find it helpful
