### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by ctron** [flathub/org.wireshark.Wireshark#8]
Installing wireshark via flatpak, I am unable to load a "pcap" file.

When I try to load a file, the "open file" dialog shows me a nearly empty file system.

**Comment by muelli** [comment]
this is expected: https://github.com/flathub/org.wireshark.Wireshark/blob/53dd239248af92a648ed1ed2dec5f965598dd0ca/org.wireshark.Wireshark.yml#L13

You can load and save files from your "public" folder. To add further exceptions to this policy, you can run smth like `flatpak --user  override --filesystem=/path/to/read-write:rw org.wireshark.WireShark`.

The upstream bug report is here: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15507
feel free to weigh in there.

**Comment by ctron** [comment]
> this is expected: 

If this is expected, it would be great to show this in the description of the flathub page.

> The upstream bug report is here: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15507
feel free to weigh in there.

Wouldn't it be an alternative to use GTK then? I know this works for other applications.

**Comment by muelli** [comment]
> Wouldn't it be an alternative to use GTK then? I

well. yes, but wireshark does not use GtK :(

I have modified the permissions in the beta build. Can you test that (e.g.  https://flathub.org/beta-repo/appstream/org.wireshark.Wireshark.flatpakref)?

**Comment by ctron** [comment]
> well. yes, but wireshark does not use GtK :(

It did in the past. And my version still does. So I assumed that this was still an option.

> I have modified the permissions in the beta build. Can you test that (e.g. https://flathub.org/beta-repo/appstream/org.wireshark.Wireshark.flatpakref)?

That works like expected. I can now also drop and drop files into Wireshark again.

Thank you.

**Comment by Lekensteyn** [comment]
Fixed in a853a48fe59ade26b6ab22da52e621e6014fd366 by sharing the home directory read-only.
